apiVersion: v1
kind: ConfigMap
metadata:
  name: agrosolutions-azurefunction-config
data:
  ASPNETCORE_URLS: http://+:8080
  AzureWebJobsStorage: "UseDevelopmentStorage=true"
  FUNCTIONS_WORKER_RUNTIME: "dotnet-isolated"
  Messaging__Host: rabbitmq
  Messaging__Port: "5672"
  Messaging__Exchange: agro-solutions.exchange
  Messaging__Destinations__0__Id: RECEIVED_SENSOR_DATA
  Messaging__Destinations__0__Queue: received-sensor-data-to-influxdb
  Messaging__Destinations__0__RoutingKey: received.sensor.data
  Messaging__Destinations__1__Id: RECEIVED_SENSOR_DATA
  Messaging__Destinations__1__Queue: received-sensor-data-to-alerts
  Messaging__Destinations__1__RoutingKey: received.sensor.data
  WeatherService__Url: https://api.open-meteo.com
  InfluxDB__Url: http://agrosolutions-ingest-influxdb:8086
  InfluxDB__Username: agrosolutions-admin
  InfluxDB__Org: agrosolutions-org
  InfluxDB__Bucket: agrosolutions-bucket
  RabbitMQConnection: "amqp://guest:guest@rabbitmq:5672/"
