apiVersion: v1
kind: Secret
metadata:
  name: agrosolutions-azurefunction-secret
type: Opaque
stringData:
  Messaging__Username: guest
  Messaging__Password: guest
  InfluxDB__Password: "agrosolutionsAdmin123$"
  InfluxDB__Token: "Je2LUfYXX9o10pAcYgzsG8tWeRlR5qwKjpAqlV_sf-HyD09G2-eG90yyOXWa6tNVDtwKzq_zshT6XXd4FYBi3A=="
