apiVersion: v1
kind: Service
metadata:
  name: agrosolutions-alert-functions
spec:
  type: NodePort
  selector:
    app: agrosolutions-alert-functions
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
