apiVersion: v1
kind: ConfigMap
metadata:
  name: agrosolutions-alerts-config
data:
  ASPNETCORE_URLS: http://+:8080
  AzureWebJobsStorage: "UseDevelopmentStorage=true"
  FUNCTIONS_WORKER_RUNTIME: "dotnet-isolated"
  Messaging__Host: rabbitmq
  Messaging__Port: "5672"
  Messaging__Exchange: agro-solutions.exchange
  Messaging__Destinations__0__Id: RECEIVED_SENSOR_DATA
  Messaging__Destinations__0__Queue: received-sensor-data-to-influxdb
  Messaging__Destinations__0__RoutingKey: received.sensor.data
  WeatherService__Url: https://api.open-meteo.com
  InfluxDB__Url: "http://influxdb:8086"
  InfluxDB__Username: "agrosolutions-admin"
  InfluxDB__Org: "agrosolutions-org"
  InfluxDB__Bucket: "agrosolutions-bucket"
  GrafanaLoki__Url: http://loki:3100
  RabbitMQConnection: "amqp://guest:guest@rabbitmq:5672/"
